version: "3.8"

name: sobesity-be

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - 5150:5150

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5454:5432

  migrator:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      target: migrator


volumes:
  pgdata:
