version: "3.8"

name: test-sobesity

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - 7777:5432

  migrator:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      target: migrator

