version: "3.8"

services:
  builder:
    build:
      context: ./
      dockerfile: ./etc/backend/Dockerfile
      target: builder
    volumes:
      - ./pyproject.toml:/code/pyproject.toml
      - ./poetry.lock:/code/poetry.lock
