version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./etc/backend/Dockerfile
      target: dev
    env_file:
      - ./etc/backend/env/dev.env
    depends_on:
      - db
    volumes:
      - ./src/sobesity:/code/sobesity
      - ./src/tests:/code/tests
      - ./src/alembic:/code/alembic
      - ./pyproject.toml:/code/pyproject.toml
      - ./poetry.lock:/code/poetry.lock
    ports:
      - 5150:5150



  db:
    image: postgres:14.6
    volumes:
      - ./etc/db/entypoints:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./etc/db/env/dev.env
    ports:
      - 5454:5432

  migrator:
    build:
      context: ./
      dockerfile: ./etc/backend/Dockerfile
      target: migrator
    env_file:
      - ./etc/backend/env/dev.env
    depends_on:
      - db
    volumes:
      - ./src/alembic/:/code/alembic/


volumes:
  pgdata:
