version: "3.8"

name: test-sobesity

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    depends_on:
      db:
        condition: service_started
      migrator:
        condition: service_completed_successfully

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - 7777:5432

  migrator:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      target: migrator
    depends_on:
      - db

